
# Revision of correlation run, e.g., v1a, gold253, gold261, gold262
REV  := v1

# Release version, e.g., 1
REL  := 1

# Name of site; used for ./filelists_<SITE>/
SITE := mpifr

# Top-level directory for Correlator output, any experiment
EXPROOT := /Exps/

